-- Fishing Overhaul (Milestone 3, user spec 2026-07-27).
--
-- Five jobs, all riding the game's own fishing flow (offline RE: rod_uber/char_uber dumps):
--   * LOOT TABLES: every BP_River_C's Loottable (per-instance TArray, no DataTable) is rewritten
--     from the generated spec below -- three island groups (starter/mid/late), per-10000 weights.
--     The whole cast/bite/catch flow runs on the OWNING CLIENT, so each machine writing its own
--     rivers IS per-player luck: your diamond rod doubles YOUR odds, not your co-op partner's.
--   * LUCK MULTIPLIERS: the rare+jackpot band scales by storm x2, dawn/dusk x1.5, diamond rod x2
--     (multiplicative, up to x6); commons shrink to keep the table at 10000. Tables are rebuilt
--     on every state flip (weather bus, IsDay watchdog, hand rebuild).
--   * DIAMOND ROD: the content-pak row (10x durability) is T5-typed -- new cooked TOOL rows are
--     the proven world-load crash -- so the game's two hardcoded class switches don't know it.
--     The mod seats the real BP_HandItem_FishingRod_C on equip and routes clicks to the pawn's
--     own Interaction_FishingRod(), which drains OUR item's durability through the shared path.
--   * BITE SPLASH: the game plays S_FishingRod_Splash at 1.0 exactly when a fish bites; the mod
--     layers (fishing_splash_gain - 1) more on top at the bobber -- "300% splash when you hook".
--   * SKILLSHOT: 5% of bites, the catch click lands a leaf instead and a sliding-marker bar
--     appears; a second click inside the golden zone guarantees a rare/jackpot roll (diamond rod:
--     smaller zone, jackpot-only). Since Catch() is VM-internal (unhookable), "instead" is done
--     by swapping the bobber's river to an all-leaf table for that one catch, then restoring.
--
-- Fished-up rods arrive "worn": a fresh rod item appearing in the inventory right after a catch
-- click is stamped a random durability via the game's own OverwriteAndSaveItemAtIndex (the wand's
-- proven in-place slot rewrite). A fresh DIAMOND rod rolls worn-vs-full by the two table entries'
-- own weights -- the catch path can't tell us which entry won, but the ratio reproduces it.
local F = {}
local ctx

--------------------------------------------------------------------- generated drop spec
-- GENERATED by tools/gen_fishing_tables.py -- regenerate there, don't hand-edit (the script
-- asserts totals, band caps and the rod/gold splits, and emits docs/FISHING.md percentages).
-- w = weight per 10000. tier "rare"/"jackpot" = the luck-multiplier band. specialty = replaced
-- per-river with that island's vanilla signature item (mid group only).
local TABLES = {
  starter = {
    { cls = "BP_Leaf_Item_C", w = 3450 },  -- Leaf
    { cls = "BP_Raspberry_Item_C", w = 950 },  -- Raspberry
    { cls = "BP_Clay_Item_C", w = 950 },  -- Clay
    { cls = "BP_Stick_Item_C", w = 950 },  -- Stick
    { cls = "BP_Sand_Item_C", w = 950 },  -- Sand
    { cls = "BP_Cotton_Item_C", w = 950 },  -- Cotton
    { cls = "BP_Wood_Waste_Item_C", w = 600 },  -- Wood Waste
    { cls = "BP_Scrap_Metal_Item_C", w = 500 },  -- Scrap Metal
    { cls = "BP_Glass_Item_C", w = 200 },  -- Glass
    { cls = "BP_Mushroom_Item_C", w = 160 },  -- Mushroom
    { cls = "BP_Sapling_Oak_Item_C", w = 80 },  -- Oak Sapling
    { cls = "BP_BirchSapling_Item_C", w = 80 },  -- Birch Sapling
    { cls = "BP_Egg_Item_C", w = 76, tier = "rare" },  -- Chicken Egg
    { cls = "BP_FishingRod_Item_C", w = 45, tier = "rare" },  -- Fishing Rod (worn)
    { cls = "BP_Seed_Cotton_Item_C", w = 20 },  -- Cotton Seed
    { cls = "BP_Diamond_Item_C", w = 20, tier = "jackpot" },  -- Diamond
    { cls = "BP_DiamondFishingRod_Item_C", w = 5, tier = "rare" },  -- Diamond Rod (worn)
    { cls = "BP_DiamondFishingRod_Item_C", w = 5, tier = "jackpot" },  -- Diamond Rod (full)
    { cls = "BP_SolarPanel_Item_C", w = 5, tier = "jackpot" },  -- Solar Panel
    { cls = "BP_GoldEgg_Item_C", w = 4, tier = "jackpot" },  -- Gold Egg
  },
  mid = {
    { cls = "BP_Leaf_Item_C", w = 1980 },  -- Leaf
    { specialty = true, cls = false, w = 900 },  -- Island specialty
    { cls = "BP_Raspberry_Item_C", w = 850 },  -- Raspberry
    { cls = "BP_Stick_Item_C", w = 850 },  -- Stick
    { cls = "BP_Sand_Item_C", w = 850 },  -- Sand
    { cls = "BP_Cotton_Item_C", w = 850 },  -- Cotton
    { cls = "BP_Clay_Item_C", w = 850 },  -- Clay
    { cls = "BP_Scrap_Metal_Item_C", w = 600 },  -- Scrap Metal
    { cls = "BP_Wood_Waste_Item_C", w = 500 },  -- Wood Waste
    { cls = "BP_IronOre_Item_C", w = 400 },  -- Iron Ore
    { cls = "BP_CopperOre_Item_C", w = 300 },  -- Copper Ore
    { cls = "BP_Glass_Item_C", w = 240 },  -- Glass
    { cls = "BP_Mushroom_Item_C", w = 160 },  -- Mushroom
    { cls = "BP_MapleSapling_Item_C", w = 80 },  -- Maple Sapling
    { cls = "BP_AlderSapling_Item_C", w = 80 },  -- Alder Sapling
    { cls = "BP_Seed_Tomato_Item_C", w = 80 },  -- Tomato Seeds
    { cls = "BP_Seed_Paprika_Item_C", w = 80 },  -- Paprika Seeds
    { cls = "BP_Egg_Item_C", w = 76, tier = "rare" },  -- Chicken Egg
    { cls = "BP_FishingRod_Item_C", w = 72, tier = "rare" },  -- Fishing Rod (worn)
    { cls = "BP_Truffle_Item_C", w = 57, tier = "jackpot" },  -- Truffle
    { cls = "BP_Diamond_Item_C", w = 40, tier = "jackpot" },  -- Diamond
    { cls = "BP_CableConnectorSmall_Item_C", w = 40, tier = "rare" },  -- Cable (wire)
    { cls = "BP_KS_FishStatue_Item_C", w = 20, tier = "jackpot" },  -- Fish Statue
    { cls = "BP_SolarPanel_Item_C", w = 15, tier = "jackpot" },  -- Solar Panel
    { cls = "BP_DiamondFishingRod_Item_C", w = 10, tier = "jackpot" },  -- Diamond Rod (full)
    { cls = "BP_DiamondFishingRod_Item_C", w = 8, tier = "rare" },  -- Diamond Rod (worn)
    { cls = "BP_AutoFisher_Item_C", w = 5, tier = "jackpot" },  -- Algae Drone
    { cls = "BP_GoldEgg_Item_C", w = 4, tier = "jackpot" },  -- Gold Egg
    { cls = "BP_GoldTruffle_Item_C", w = 3, tier = "jackpot" },  -- Gold Truffle
  },
  late = {
    { cls = "BP_Algae_Item_C", w = 3950 },  -- Algae
    { cls = "BP_IronOre_Item_C", w = 800 },  -- Iron Ore
    { cls = "BP_Leaf_Item_C", w = 780 },  -- Leaf
    { cls = "BP_Scrap_Metal_Item_C", w = 600 },  -- Scrap Metal
    { cls = "BP_CopperOre_Item_C", w = 600 },  -- Copper Ore
    { cls = "BP_QuartzOre_Item_C", w = 500 },  -- Quartz Ore
    { cls = "BP_Sapling_Pine_Item_C", w = 500 },  -- Pine Sapling
    { cls = "BP_Wood_Waste_Item_C", w = 400 },  -- Wood Waste
    { cls = "BP_Glass_Item_C", w = 300 },  -- Glass
    { cls = "BP_Sand_Item_C", w = 250 },  -- Sand
    { cls = "BP_Clay_Item_C", w = 250 },  -- Clay
    { cls = "BP_CobaltOre_Item_C", w = 240 },  -- Cobalt Ore
    { cls = "BP_Circuitboard_Item_C", w = 160, tier = "rare" },  -- Circuitboard
    { cls = "BP_Truffle_Item_C", w = 152, tier = "jackpot" },  -- Truffle
    { cls = "BP_Diamond_Item_C", w = 100, tier = "jackpot" },  -- Diamond
    { cls = "BP_FishingRod_Item_C", w = 90, tier = "rare" },  -- Fishing Rod (worn)
    { cls = "BP_Battery_Item_C", w = 80, tier = "rare" },  -- Battery
    { cls = "BP_CableConnectorSmall_Item_C", w = 80, tier = "rare" },  -- Cable (wire)
    { cls = "BP_Egg_Item_C", w = 57, tier = "rare" },  -- Chicken Egg
    { cls = "BP_SolarPanel_Item_C", w = 30, tier = "jackpot" },  -- Solar Panel
    { cls = "BP_AutoFisher_Item_C", w = 20, tier = "jackpot" },  -- Algae Drone
    { cls = "BP_DiamondFishingRod_Item_C", w = 20, tier = "jackpot" },  -- Diamond Rod (full)
    { cls = "BP_KS_FishStatue_Item_C", w = 20, tier = "jackpot" },  -- Fish Statue
    { cls = "BP_DiamondFishingRod_Item_C", w = 10, tier = "rare" },  -- Diamond Rod (worn)
    { cls = "BP_GoldTruffle_Item_C", w = 8, tier = "jackpot" },  -- Gold Truffle
    { cls = "BP_GoldEgg_Item_C", w = 3, tier = "jackpot" },  -- Gold Egg
  },
}
F.TABLES = TABLES

-- The 12 rivers of MainLevel, keyed by world position (instance NAMES are not stable across
-- loads; positions are level data). Offline census 2026-07-27 (loothunt over MainLevel.umap),
-- islands named via WC_Map canvas slots + the world->map transform (see the fishing-loot memory).
-- group: starter = the spawn ring, mid = the crop islands (each keeps its vanilla signature item
-- as `specialty`), late = the far/winter islands. Saplings per group match the biome's trees.
local RIVERS = {
  { x = 3576,    y = -7019,   group = "starter" },                                -- NewStart
  { x = 183442,  y = -71195,  group = "starter" },                                -- Chair
  { x = 140895,  y = 115673,  group = "starter" },                                -- LowerNice north bank
  { x = -137107, y = -44448,  group = "mid", specialty = "BP_Carrot_Item_C" },    -- GoldenMid (carrots)
  { x = 47872,   y = 88401,   group = "mid", specialty = "BP_Wheat_Item_C" },     -- Land (wheat)
  { x = -177869, y = 144840,  group = "mid", specialty = "BP_Algae_Item_C" },     -- Worm west (algae)
  { x = -182335, y = 173634,  group = "mid", specialty = "BP_Algae_Item_C" },     -- Worm east (algae)
  { x = 139427,  y = 111531,  group = "mid", specialty = "BP_Sunflower_Item_C" }, -- LowerNice (sunflower)
  { x = -114313, y = 423542,  group = "late" },                                   -- Start
  { x = -226098, y = -269373, group = "late" },                                   -- WildWinter
  { x = 70182,   y = 353680,  group = "late" },                                   -- UShape
  { x = 487688,  y = 65143,   group = "late" },                                   -- SnowCave
}
F.RIVERS = RIVERS

--------------------------------------------------------------------- pure logic (unit-tested)
-- Combined rare+jackpot multiplier for the current conditions.
function F.luckMult(diamond, storm, twilight, cfg)
  cfg = cfg or {}
  local m = 1.0
  if diamond then m = m * (cfg.diamond or 2.0) end
  if storm then m = m * (cfg.storm or 2.0) end
  if twilight then m = m * (cfg.twilight or 1.5) end
  return m
end

-- Compose a river's weight list: specialty substitution + the multiplier band. tier entries
-- scale by `mult`; the rest shrink so the table still sums to its original total (the game's
-- GetRandomItemWeighted just sums whatever is there, but honest percentages need the invariant).
-- Returns { {cls=short, w=int, tier=...}, ... } -- classes still short names, resolution is I/O.
function F.composeTable(group, specialty, mult)
  local spec = TABLES[group]
  if not spec then return nil end
  local total, bonus = 0, 0
  for _, e in ipairs(spec) do
    total = total + e.w
    if e.tier then bonus = bonus + e.w end
  end
  local m = mult or 1.0
  -- defensive cap: the band may never swallow the table (late x6 = 49.8%, well clear)
  if bonus > 0 and m * bonus >= total then m = (total * 0.9) / bonus end
  local shrink = (bonus < total) and (total - m * bonus) / (total - bonus) or 1.0
  local out = {}
  for _, e in ipairs(spec) do
    local cls = e.cls
    if e.specialty then cls = specialty end
    if cls then
      local w = e.tier and (e.w * m) or (e.w * shrink)
      w = math.floor(w + 0.5)
      if w < 1 then w = 1 end
      out[#out + 1] = { cls = cls, w = w, tier = e.tier }
    end
  end
  -- integer drift lands on the big base entry (always entry 1: Leaf/Algae), keeping sum == total
  local sum = 0
  for _, e in ipairs(out) do sum = sum + e.w end
  if out[1] then out[1].w = math.max(1, out[1].w + (total - sum)) end
  return out
end

-- The skillshot's guaranteed pool: the group's rare+jackpot entries (jackpot-only for diamond).
function F.rewardPool(group, jackpotOnly)
  local out = {}
  for _, e in ipairs(TABLES[group] or {}) do
    if e.tier and e.cls and (not jackpotOnly or e.tier == "jackpot") then out[#out + 1] = e end
  end
  return out
end

-- Weighted pick with an injected 0..1 roll (deterministic under test).
function F.weightedPick(pool, r)
  local total = 0
  for _, e in ipairs(pool) do total = total + e.w end
  if total <= 0 then return nil end
  local x, acc = r * total, 0
  for _, e in ipairs(pool) do
    acc = acc + e.w
    if x < acc then return e end
  end
  return pool[#pool]
end

-- Nearest baked river to a world point (rivers are km apart; the bobber is metres from the pawn).
function F.nearestRiver(x, y)
  local best, bestD
  for _, r in ipairs(RIVERS) do
    local d = (x - r.x) ^ 2 + (y - r.y) ^ 2
    if not bestD or d < bestD then best, bestD = r, d end
  end
  return best, bestD
end

-- Skillshot marker position 0..1: a ping-pong sweep, `period` seconds out and back.
function F.markerPos(elapsed, period)
  if not period or period <= 0 then period = 1.6 end
  local ph = (elapsed % period) / period
  return ph < 0.5 and ph * 2 or 2 - ph * 2
end

function F.zoneHit(pos, center, width)
  -- the epsilon eats float dust at the exact drawn edge: what looks in, IS in
  return math.abs(pos - center) <= width / 2 + 1e-9
end

-- A fished-up rod's remaining durability from a 0..1 roll.
function F.wornDurability(r, maxDur, minFrac, maxFrac)
  local frac = (minFrac or 0.1) + r * ((maxFrac or 0.6) - (minFrac or 0.1))
  local d = math.floor(maxDur * frac)
  if d < 1 then d = 1 end
  if d > maxDur then d = maxDur end
  return d
end

-- P(a fresh diamond rod from the table was the WORN entry): the two entries' own weight ratio.
function F.wornShare(group, shortCls)
  local worn, full = 0, 0
  for _, e in ipairs(TABLES[group] or {}) do
    if e.cls == shortCls then
      if e.tier == "jackpot" then full = full + e.w else worn = worn + e.w end
    end
  end
  if worn + full <= 0 then return 1.0 end
  return worn / (worn + full)
end

--------------------------------------------------------------------- helpers
local function onGameThread(fn)
  if ExecuteInGameThread then
    if pcall(ExecuteInGameThread, fn) then return end
  end
  pcall(fn)
end

local function defer(ms, fn)
  if not pcall(ExecuteWithDelay, ms, fn) then onGameThread(fn) end
end

-- Schedule-ONLY defer for hook bodies (see qol.lua: the inline fallback is the one thing a hook
-- body may never do -- re-entrant hook-body-touches-UObjects native-crashes uncatchably).
local function deferOnly(ms, fn)
  if pcall(ExecuteWithDelay, ms, fn) then return true end
  return false
end

local function fullFuncPath(obj, fnName)
  local full
  pcall(function()
    local cls = obj:GetClass()
    if not (cls and cls.ForEachFunction) then return end
    cls:ForEachFunction(function(fn)
      local n = ""
      pcall(function() n = fn:GetFName():ToString() end)
      if n == fnName then pcall(function() full = fn:GetFullName() end) end
    end)
  end)
  if full then return (full:gsub("^%S+%s+", "")) end
  return nil
end

local function cfg(k) return ctx.config.get(k) end

--------------------------------------------------------------------- state
local hooked = {}        -- key -> { preId, postId, path } (cleared on world change, qol pattern)
local hookWorldPc        -- local controller fullname the current registrations belong to
local classCache = {}    -- short class name -> UClass | false (classes RELOAD on world change)
local tablesBroken = false -- struct-array assignment failed -> stop trying for the session

local stormNow = false
local twilightUntil = -1e9
local lastIsDay = nil    -- nil until first read; flips open the twilight window
local dayToken = 0
local diamondHeld = false
local lastAppliedKey = nil

local lastClickAt = -1e9 -- accepted (debounced) rod-click time
local lastBiteAt = -1e9  -- PlayerCanCatch flip time
local lastSeatAt = -1e9
local sweepToken = 0
local freshRodSlots = {} -- snapshot at bite: { [idx] = true } of already-fresh rod slots
local mgKnownReward = nil -- "worn"|"full": the skillshot TOLD us which rod entry it granted

-- minigame
local mgReady = nil      -- nil = unprobed, true/false after the widget probe
local mgPending = false  -- bite rolled the 5%; the NEXT catch click reveals the bar
local mgActive = false
local mgToken = 0
local mgStart = 0
local mgCenter, mgWidth = 0.5, 0.18
local mgDiamond = false
local mgGroup = "starter"
local mgRiver = nil      -- the leaf-swapped river actor (restored on resolve)
local mgW = {}           -- widget refs { bg, zone, mark, markSlot }
local forceMini = false  -- sps_fish_mini: arm on every bite (live testing)

--------------------------------------------------------------------- class resolution
local function resolveClass(short)
  local c = classCache[short]
  if c ~= nil then return c or nil end
  local m = ctx.map.fishing
  local dir = ctx.map.items and ctx.map.items.assetDir
  local path
  if short == m.rodHandClass then
    path = m.rodHandPath
  elseif dir then
    path = dir .. short:gsub("_C$", "") .. "." .. short
  end
  local cls = ctx.uehelp.classByName(short, path)
  classCache[short] = cls or false
  return cls
end

--------------------------------------------------------------------- table writer
local function currentMult()
  local twilight = os.clock() < twilightUntil
  return F.luckMult(diamondHeld, stormNow, twilight, {
    diamond = cfg("fishing_diamond_mult"),
    storm = cfg("fishing_storm_mult"),
    twilight = cfg("fishing_twilight_mult"),
  }), twilight
end

-- Turn a composed spec into the real struct array and assign it. Weights of classes that don't
-- resolve (no content pak -> no diamond/gold classes) fold into entry 1 (the Leaf/Algae base),
-- keeping the total honest. Returns true only when the readback length matches.
local function writeRiver(river, entries)
  local m = ctx.map.fishing
  local arr, fold = {}, 0
  for _, e in ipairs(entries) do
    local cls = resolveClass(e.cls)
    if cls then
      arr[#arr + 1] = { [m.lootItemField] = cls, [m.lootWeightField] = e.w }
    else
      fold = fold + e.w
    end
  end
  if #arr < 3 then return false end -- even the base classes missing = nothing sane to write
  if fold > 0 then arr[1][m.lootWeightField] = arr[1][m.lootWeightField] + fold end
  if not ctx.uehelp.set(river, m.loottableProp, arr) then return false end
  local got
  pcall(function() got = river[m.loottableProp] end)
  return #ctx.uehelp.arrayItems(got) == #arr
end

-- Rewrite EVERY resident river from the spec at the current multiplier. Idempotent and cheap
-- (12 assignments); called on world entry and every luck-state flip.
function F.applyTables(reason)
  if tablesBroken or not (cfg("fishing_enabled") and cfg("fishing_tables")) then return end
  local m = ctx.map.fishing
  local rivers = ctx.uehelp.findAll(m.riverClass)
  if #rivers == 0 then return end
  local mult, twilight = currentMult()
  local wrote, failed = 0, 0
  for _, river in ipairs(rivers) do
    if ctx.uehelp.isValid(river) then
      local loc
      pcall(function() loc = river:K2_GetActorLocation() end)
      loc = ctx.uehelp.vec(loc)
      if loc then
        local baked = F.nearestRiver(loc.X, loc.Y)
        local spec = baked and F.composeTable(baked.group, baked.specialty, mult)
        if spec and writeRiver(river, spec) then wrote = wrote + 1 else failed = failed + 1 end
      end
    end
  end
  lastAppliedKey = string.format("%s|%s|%s", tostring(diamondHeld), tostring(stormNow), tostring(twilight))
  if wrote > 0 then
    ctx.log.info(string.format("fishing: %d/%d river tables set (%s, x%.1f luck band)",
      wrote, #rivers, tostring(reason), mult))
  elseif failed > 0 then
    -- every write failed on real rivers: the struct-array assignment doesn't take on this build.
    -- Stand down for the session -- vanilla loot beats retry-spam (splash/diamond shim still run).
    tablesBroken = true
    ctx.log.error("fishing: river Loottable assignment failed on every river -- vanilla loot stands")
  end
end

local function checkMult(reason)
  local _, twilight = currentMult()
  local key = string.format("%s|%s|%s", tostring(diamondHeld), tostring(stormNow), tostring(twilight))
  if key ~= lastAppliedKey then onGameThread(function() F.applyTables(reason) end) end
end

--------------------------------------------------------------------- twilight watchdog
-- IsDay sampling on a slow self-rechaining one-shot (the storms.naturalWatchdog shape --
-- free-running UObject timers are the proven native crash; this touches one prop per pass,
-- re-found fresh, fully guarded). A flip opens the fishing_twilight_secs window.
local function dayWatch(tok)
  local ms = math.max(5, math.floor((tonumber(cfg("fishing_daywatch_secs")) or 20) * 1000))
  pcall(ExecuteWithDelay, ms, ctx.log.guard("fishing.daywatch", function()
    if tok ~= dayToken then return end
    onGameThread(function()
      if tok ~= dayToken then return end
      local w = ctx.map.weather
      local mgr = w and ctx.uehelp.findFirst(w.managerClass)
      if mgr and w.isDayProp then
        local ok, v = ctx.uehelp.get(mgr, w.isDayProp)
        if ok and type(v) == "boolean" then
          if lastIsDay ~= nil and v ~= lastIsDay then
            twilightUntil = os.clock() + (tonumber(cfg("fishing_twilight_secs")) or 300)
            ctx.log.info(v and "fishing: the sun rises -- the waters stir (x1.5 luck)"
                           or "fishing: the sun sets -- the waters stir (x1.5 luck)")
          end
          lastIsDay = v
        end
      end
      checkMult("twilight")  -- catches window expiry too
      dayWatch(tok)
    end)
  end))
end

--------------------------------------------------------------------- held-item identity
-- CurItemdataInHand's members carry GUID-suffixed FNames; resolve them once per session off the
-- pawn class (the wand's proven recipe -- S_Item.DisplayName reads empty, ItemActor is the truth).
local structMembers
local structMemberTries = 0
local function itemStructMembers(pawn)
  if structMembers ~= nil then return structMembers or nil end
  local prop = ctx.map.wand and ctx.map.wand.handItemDataProp
  if not prop then return nil end
  local found
  pcall(function()
    local cls = pawn:GetClass()
    if not (cls and cls.ForEachProperty) then return end
    cls:ForEachProperty(function(pr)
      local pn
      pcall(function() pn = pr:GetFName():ToString() end)
      if pn == prop then
        local st
        pcall(function() st = pr:GetStruct() end)
        if not st then pcall(function() st = pr.Struct end) end
        if st and st.ForEachProperty then
          local mm = {}
          st:ForEachProperty(function(mp)
            local mn
            pcall(function() mn = mp:GetFName():ToString() end)
            if mn then mm[mn:match("^(.-)_%d+_") or mn] = mn end
          end)
          if next(mm) then found = mm end
        end
      end
    end)
  end)
  if found then
    structMembers = found
  else
    structMemberTries = structMemberTries + 1
    if structMemberTries >= 5 then structMembers = false end
  end
  return structMembers or nil
end

-- "vanilla" | "diamond" | nil for the item currently in this pawn's hand.
local function heldRodKind(pawn)
  local m = ctx.map.fishing
  local wm = ctx.map.wand
  local classFmt = ctx.map.items and ctx.map.items.classFmt
  if not (wm and wm.handItemDataProp and classFmt) then return nil end
  local ok, data = ctx.uehelp.get(pawn, wm.handItemDataProp)
  if not (ok and data ~= nil) then return nil end
  local members = itemStructMembers(pawn)
  if not (members and members.ItemActor) then return nil end
  local ia
  pcall(function() ia = data[members.ItemActor] end)
  if not ctx.uehelp.isValid(ia) then return nil end -- empty slot = null wrapper, never touch it
  local cn
  pcall(function() cn = ia:GetFName():ToString() end)
  if cn == m.rodItemClass then return "vanilla" end
  if m.diamondRow and cn == string.format(classFmt, m.diamondRow) then return "diamond" end
  return nil
end

--------------------------------------------------------------------- worn-rod stamping
local function durabilitySavedata(n)
  -- byte-exact copy of the game's own .sav shape (see features/wand.lua)
  return "{\r\n\t\"Durability\": " .. math.floor(n) .. "\r\n}"
end

local function rodShortNames()
  local m = ctx.map.fishing
  local classFmt = ctx.map.items and ctx.map.items.classFmt
  local names = { [m.rodItemClass] = "vanilla" }
  if classFmt and m.diamondRow then names[string.format(classFmt, m.diamondRow)] = "diamond" end
  return names
end

-- Indices (game 0-based) of inventory slots holding a FACTORY-FRESH rod (no Durability savedata).
local function freshRods(pawn)
  local m = ctx.map.fishing
  local wm = ctx.map.wand
  local out = {}
  local inv
  pcall(function() inv = pawn[wm.inventorySystemProp or "InventorySystem"] end)
  if not ctx.uehelp.isValid(inv) then return out end
  local arr
  pcall(function() arr = inv[m.invArrayProp] end)
  if arr == nil then return out end
  local names = rodShortNames()
  local i = 0
  pcall(function()
    arr:ForEach(function(_, el)
      local e
      pcall(function() e = el:get() end)
      if e == nil then e = el end
      local cls, sd
      pcall(function() cls = e[wm.slotItemField] end)
      if ctx.uehelp.isValid(cls) then
        local cn
        pcall(function() cn = cls:GetFName():ToString() end)
        local kind = cn and names[cn]
        if kind then
          pcall(function()
            local raw = e[wm.slotSavedataField]
            if type(raw) == "string" then sd = raw else sd = raw:ToString() end
          end)
          if not (type(sd) == "string" and sd:find("Durability", 1, true)) then
            out[i] = kind
          end
        end
      end
      i = i + 1
    end)
  end)
  return out
end

-- Stamp every fresh rod that APPEARED since the bite snapshot. Vanilla rods are always worn;
-- diamond rods roll worn-vs-full by the table entries' weight ratio (or by what the skillshot
-- said it granted). Runs a few spaced passes -- the spawned loot flies to the player, but a slow
-- pickup must not slip through at full durability.
local function sweepNewRods(pawn, group, tok)
  if tok ~= sweepToken or not ctx.uehelp.isValid(pawn) then return end
  local m = ctx.map.fishing
  local wm = ctx.map.wand
  if not (wm and wm.overwriteSlotFn and wm.slotItemField and wm.slotQtyField and wm.slotSavedataField) then return end
  local now = freshRods(pawn)
  for idx, kind in pairs(now) do
    if not freshRodSlots[idx] then
      freshRodSlots[idx] = kind -- one stamp per slot per bite window
      local short = (kind == "diamond") and string.format(ctx.map.items.classFmt, m.diamondRow) or m.rodItemClass
      local maxDur = (kind == "diamond") and m.diamondDurability or m.rodDurability
      local worn = true
      if kind == "diamond" then
        if mgKnownReward then
          worn = (mgKnownReward == "worn")
          mgKnownReward = nil
        else
          worn = math.random() < F.wornShare(group or "starter", short)
        end
      end
      if worn then
        local dur = F.wornDurability(math.random(), maxDur,
          tonumber(cfg("fishing_rod_wear_min")) or 0.1, tonumber(cfg("fishing_rod_wear_max")) or 0.6)
        local inv
        pcall(function() inv = pawn[wm.inventorySystemProp or "InventorySystem"] end)
        local cls = resolveClass(short)
        if ctx.uehelp.isValid(inv) and cls then
          local slot = {
            [wm.slotItemField] = cls,
            [wm.slotQtyField] = 1,
            [wm.slotSavedataField] = durabilitySavedata(dur),
          }
          local ok = ctx.uehelp.call(inv, wm.overwriteSlotFn, slot, idx)
          if ok then
            ctx.log.info(string.format("fishing: the river's old rod shows its years (%d/%d durability, slot %d)",
              dur, maxDur, idx))
            -- redraw the bar the game never refreshes on authority (the wand's lesson)
            local pc
            pcall(function() pc = pawn[wm.localControllerProp or "LocalController"] end)
            local hb
            if ctx.uehelp.isValid(pc) then pcall(function() hb = pc[wm.hotbarWidgetProp or "UI_Hotbar"] end) end
            if ctx.uehelp.isValid(hb) and wm.hotbarRefreshFn then ctx.uehelp.call(hb, wm.hotbarRefreshFn) end
            if wm.invChangedFn then ctx.uehelp.call(inv, wm.invChangedFn) end
          end
        end
      else
        ctx.log.info("fishing: a PRISTINE diamond rod out of the water -- jackpot")
      end
    end
  end
end

local function scheduleSweeps(pawn, group)
  sweepToken = sweepToken + 1
  local tok = sweepToken
  for _, ms in ipairs({ 700, 2500, 6000 }) do
    defer(ms, ctx.log.guard("fishing.sweep", function()
      onGameThread(function() sweepNewRods(pawn, group, tok) end)
    end))
  end
end

--------------------------------------------------------------------- skillshot bar (UI)
local function teardownBar()
  for _, k in ipairs({ "mark", "zone", "bg" }) do
    local w = mgW[k]
    if w then pcall(function() w:RemoveFromParent() end) end
  end
  mgW = {}
end

local function overlayCanvas()
  local q = ctx.map.qol or {}
  local pc = ctx.uehelp.localController(ctx.map.player and ctx.map.player.controllerClass)
  if not ctx.uehelp.isValid(pc) then return nil end
  local overlay
  pcall(function() overlay = pc[q.overlayProp or "PlayerOverlay"] end)
  if not ctx.uehelp.isValid(overlay) then return nil end
  local root
  pcall(function() root = overlay.WidgetTree.RootWidget end)
  if not ctx.uehelp.isValid(root) then return nil end
  return root, overlay
end

local function makeImage(canvas, overlay, x, y, w, h, color, z)
  local m = ctx.map.fishing
  local imgCls = StaticFindObject and StaticFindObject(m.imagePath)
  if not ctx.uehelp.isValid(imgCls) then return nil end
  local img, slot
  local ok = pcall(function()
    img = StaticConstructObject(imgCls, overlay)
    slot = canvas[m.canvasAddFn](canvas, img)
    slot:SetPosition({ X = x, Y = y })
    slot:SetSize({ X = w, Y = h })
    slot:SetZOrder(z or 60)
    img:SetColorAndOpacity({ R = color[1], G = color[2], B = color[3], A = color[4] })
  end)
  if not (ok and ctx.uehelp.isValid(img)) then
    if img then pcall(function() img:RemoveFromParent() end) end
    return nil
  end
  return img, slot
end

-- One-time capability probe: construct + place + remove an invisible Image. StaticConstructObject
-- of raw UMG onto a live canvas is unproven on this build -- if it can't work, the minigame never
-- arms (no leaf-swaps, no lost bites) instead of failing with the bar already owed to the player.
local function probeBar()
  if mgReady ~= nil then return end
  local canvas, overlay = overlayCanvas()
  if not canvas then return end -- menu / early; re-probed next applyAll
  local img = makeImage(canvas, overlay, 0, 0, 2, 2, { 0, 0, 0, 0 }, 1)
  if img then
    pcall(function() img:RemoveFromParent() end)
    mgReady = true
    ctx.log.debug("fishing: skillshot bar probe OK")
  else
    mgReady = false
    ctx.log.warn("fishing: raw-widget construction failed -- the skillshot minigame is disabled")
  end
end

local function markerLoop(tok)
  pcall(ExecuteWithDelay, 33, ctx.log.guard("fishing.marker", function()
    if tok ~= mgToken or not mgActive then return end
    onGameThread(function()
      if tok ~= mgToken or not mgActive then return end
      if os.clock() - mgStart > (tonumber(cfg("fishing_minigame_timeout")) or 6) then
        mgActive = false
        teardownBar()
        ctx.log.info("fishing: too slow -- the big one slips away")
        return
      end
      local slot = mgW.markSlot
      if slot then
        local barX, barY = tonumber(cfg("fishing_bar_x")) or 750, tonumber(cfg("fishing_bar_y")) or 700
        local barW = tonumber(cfg("fishing_bar_w")) or 420
        local p = F.markerPos(os.clock() - mgStart, tonumber(cfg("fishing_minigame_period")) or 1.6)
        pcall(function() slot:SetPosition({ X = barX + p * (barW - 6), Y = barY - 4 }) end)
      end
      markerLoop(tok)
    end)
  end))
end

local function buildBar()
  local canvas, overlay = overlayCanvas()
  if not canvas then return false end
  local barX, barY = tonumber(cfg("fishing_bar_x")) or 750, tonumber(cfg("fishing_bar_y")) or 700
  local barW, barH = tonumber(cfg("fishing_bar_w")) or 420, tonumber(cfg("fishing_bar_h")) or 26
  mgWidth = tonumber(cfg(mgDiamond and "fishing_minigame_zone_diamond" or "fishing_minigame_zone"))
            or (mgDiamond and 0.10 or 0.18)
  mgCenter = 0.22 + math.random() * 0.56
  local zoneColor = mgDiamond and { 0.65, 0.9, 1.0, 0.98 } or { 1.0, 0.78, 0.10, 0.95 }
  local bg = makeImage(canvas, overlay, barX, barY, barW, barH, { 0.06, 0.42, 0.10, 0.92 }, 60)
  if not bg then return false end
  local zone = makeImage(canvas, overlay, barX + (mgCenter - mgWidth / 2) * barW, barY,
    mgWidth * barW, barH, zoneColor, 61)
  local mark, markSlot = makeImage(canvas, overlay, barX, barY - 4, 6, barH + 8, { 1, 1, 1, 1 }, 62)
  if not (zone and mark) then
    mgW = { bg = bg, zone = zone, mark = mark }
    teardownBar()
    return false
  end
  mgW = { bg = bg, zone = zone, mark = mark, markSlot = markSlot }
  return true
end

--------------------------------------------------------------------- skillshot flow
local function restoreMgRiver()
  local river = mgRiver
  mgRiver = nil
  if not (river and ctx.uehelp.isValid(river)) then return end
  local baked
  local loc
  pcall(function() loc = river:K2_GetActorLocation() end)
  loc = ctx.uehelp.vec(loc)
  if loc then baked = F.nearestRiver(loc.X, loc.Y) end
  if baked then
    local mult = currentMult()
    local spec = F.composeTable(baked.group, baked.specialty, mult)
    if spec then writeRiver(river, spec) end
  end
end

-- The 5% bite: swap the bobber's river to all-leaf so the imminent catch click lands a leaf
-- ("clicking to catch INSTEAD reveals the bar"), remember it for the restore.
local function armMinigame(pawn)
  if not mgReady then return end
  local m = ctx.map.fishing
  local loc
  pcall(function() loc = pawn:K2_GetActorLocation() end)
  loc = ctx.uehelp.vec(loc)
  if not loc then return end
  local baked = F.nearestRiver(loc.X, loc.Y)
  if not baked then return end
  local river
  local bestD
  for _, r in ipairs(ctx.uehelp.findAll(m.riverClass)) do
    local rl
    pcall(function() rl = r:K2_GetActorLocation() end)
    rl = ctx.uehelp.vec(rl)
    if rl then
      local d = (rl.X - loc.X) ^ 2 + (rl.Y - loc.Y) ^ 2
      if not bestD or d < bestD then river, bestD = r, d end
    end
  end
  if not river then return end
  local leaf = resolveClass("BP_Leaf_Item_C")
  if not leaf then return end
  if not ctx.uehelp.set(river, m.loottableProp, { { [m.lootItemField] = leaf, [m.lootWeightField] = 1 } }) then
    return
  end
  mgRiver = river
  mgGroup = baked.group
  mgDiamond = (heldRodKind(pawn) == "diamond")
  mgPending = true
  mgToken = mgToken + 1
  local tok = mgToken
  -- unanswered bite window: put the table back and forget the whole thing
  defer(2000, ctx.log.guard("fishing.mgexpire", function()
    onGameThread(function()
      if tok == mgToken and mgPending then
        mgPending = false
        restoreMgRiver()
      end
    end)
  end))
end

local function grantReward(pawn)
  local pool = F.rewardPool(mgGroup, mgDiamond)
  -- only entries whose class actually resolves on this install (no pak = no diamond/gold rows)
  local live = {}
  for _, e in ipairs(pool) do
    if resolveClass(e.cls) then live[#live + 1] = e end
  end
  local e = F.weightedPick(live, math.random())
  if not e then return end
  local pc = ctx.uehelp.localController(ctx.map.player and ctx.map.player.controllerClass)
  if not ctx.uehelp.isValid(pc) then return end
  local m = ctx.map.fishing
  local isRod = (e.cls == m.rodItemClass)
    or (ctx.map.items and e.cls == string.format(ctx.map.items.classFmt, m.diamondRow))
  if isRod then mgKnownReward = (e.tier == "jackpot") and "full" or "worn" end
  freshRodSlots = freshRods(pawn) -- pre-grant snapshot: only the granted rod reads as "new"
  if ctx.items.giveByClass(pc, e.cls, 1) then
    ctx.log.info("*** SKILLSHOT! the waters yield: " .. e.cls:gsub("^BP_", ""):gsub("_Item_C$", "") .. " ***")
    if isRod then scheduleSweeps(pawn, mgGroup) else mgKnownReward = nil end
  end
end

-- Second click: freeze the marker where it is and judge it. Pure math -- the position is
-- recomputed from the same clock the render loop uses, so what you see is what is judged.
local function resolveMinigame(pawn)
  if not mgActive then return end
  mgActive = false
  local p = F.markerPos(os.clock() - mgStart, tonumber(cfg("fishing_minigame_period")) or 1.6)
  teardownBar()
  if F.zoneHit(p, mgCenter, mgWidth) then
    grantReward(pawn)
  else
    ctx.log.info(string.format("fishing: missed the %s zone (%.0f%% vs %.0f%%) -- it got away",
      mgDiamond and "diamond" or "golden", p * 100, mgCenter * 100))
  end
end

--------------------------------------------------------------------- the bite
local splashWave
local function playExtraSplash(rod)
  local gain = tonumber(cfg("fishing_splash_gain")) or 3.0
  local extra = gain - 1.0
  if extra <= 0.05 then return end
  local m = ctx.map.fishing
  if not ctx.uehelp.isValid(splashWave) then
    splashWave = StaticFindObject and StaticFindObject(m.splashWavePath)
    if not ctx.uehelp.isValid(splashWave) and LoadAsset then
      pcall(LoadAsset, (m.splashWavePath:gsub("%..*$", "")))
      splashWave = StaticFindObject and StaticFindObject(m.splashWavePath)
    end
    if not ctx.uehelp.isValid(splashWave) then return end
  end
  local loc
  pcall(function() loc = rod[m.swimmerProp]:K2_GetComponentLocation() end)
  if not loc then pcall(function() loc = rod:K2_GetActorLocation() end) end
  loc = ctx.uehelp.vec(loc)
  if not loc then return end
  local gs = StaticFindObject and StaticFindObject("/Script/Engine.Default__GameplayStatics")
  local pc = ctx.uehelp.localController(ctx.map.player and ctx.map.player.controllerClass)
  if not (gs and ctx.uehelp.isValid(pc)) then return end
  local rot = { Pitch = 0, Yaw = 0, Roll = 0 }
  -- arity fallbacks: the reflected PlaySoundAtLocation signature varies (evil_animals' recipe)
  if pcall(function() gs:PlaySoundAtLocation(pc, splashWave, loc, rot, extra, 1.0, 0.0, nil, nil, nil) end) then return end
  if pcall(function() gs:PlaySoundAtLocation(pc, splashWave, loc, rot, extra, 1.0, 0.0) end) then return end
  pcall(function() gs:PlaySoundAtLocation(pc, splashWave, loc, rot, extra, 1.0) end)
end

-- Deferred body of the ChanceForLoot hook: this rod just ticked its 1.5 s roll. A fresh
-- PlayerCanCatch=true edge IS the bite -- the game played its splash this same frame.
local function onLootTick(rod)
  if not ctx.uehelp.isValid(rod) then return end
  local m = ctx.map.fishing
  local pawn = ctx.uehelp.playerPawn(ctx.map.pawn and ctx.map.pawn.class)
  if not ctx.uehelp.isValid(pawn) then return end
  -- only the LOCAL player's rod: remote players' hand actors exist here too, but their fishing
  -- state ticks on their machine -- and this machine's inventory snapshot would be the wrong one
  local held
  pcall(function() held = pawn[ctx.map.wand.handItemProp or "CurHandItemFirstPerson"] end)
  if not ctx.uehelp.sameObject(rod, held) then return end
  local ok, canCatch = ctx.uehelp.get(rod, m.canCatchProp)
  if not (ok and canCatch == true) then return end
  if os.clock() - lastBiteAt < 1.2 then return end -- one bite, one splash
  lastBiteAt = os.clock()
  playExtraSplash(rod)
  freshRodSlots = freshRods(pawn) -- pre-catch snapshot for the worn-rod stamp
  local chance = tonumber(cfg("fishing_minigame_chance")) or 0
  if (forceMini or (chance > 0 and math.random() < chance)) and not (mgPending or mgActive) then
    armMinigame(pawn)
  end
end

--------------------------------------------------------------------- clicks
-- Debounced, deferred body of the IA_HandInteract hooks. Three jobs, in priority order:
-- resolve an active skillshot, reveal a pending one, drive the diamond rod / stamp worn rods.
local function onClick(pawn)
  if not ctx.uehelp.isValid(pawn) then return end
  if os.clock() - lastClickAt < (tonumber(cfg("fishing_click_debounce")) or 0.3) then return end
  lastClickAt = os.clock()

  if mgActive then
    resolveMinigame(pawn)
    return
  end
  if mgPending and os.clock() - lastBiteAt < 1.4 then
    -- this click is the game's own Catch() -- it lands the placeholder leaf. Reveal the bar.
    mgPending = false
    defer(250, ctx.log.guard("fishing.mgrestore", function()
      onGameThread(restoreMgRiver)  -- the leaf is already caught; put the real table back
    end))
    if buildBar() then
      mgActive = true
      mgStart = os.clock()
      mgToken = mgToken + 1
      markerLoop(mgToken)
      ctx.log.info(mgDiamond and "fishing: something HUGE -- hit the diamond zone!"
                             or "fishing: something big -- hit the golden zone!")
    else
      mgReady = false
      ctx.log.warn("fishing: skillshot bar failed to build -- minigame disabled")
    end
    return
  end

  local kind = heldRodKind(pawn)
  if kind == "diamond" and cfg("fishing_enabled") then
    -- the game's switches don't know our row -- drive its own event (cast/reel + durability)
    local m = ctx.map.fishing
    ctx.uehelp.call(pawn, m.useRodFn)
  end
  if kind and os.clock() - lastBiteAt < 1.4 then
    -- a catch attempt inside the reel window: whatever it landed may be a factory-fresh rod
    scheduleSweeps(pawn, (function()
      local loc
      pcall(function() loc = pawn:K2_GetActorLocation() end)
      loc = ctx.uehelp.vec(loc)
      local baked = loc and F.nearestRiver(loc.X, loc.Y)
      return baked and baked.group or "starter"
    end)())
  end
end

--------------------------------------------------------------------- diamond rod equip shim
local function armRodHook() end -- forward decl (defined under hooks below)

local function seatDiamond(pawn)
  local m = ctx.map.fishing
  local wm = ctx.map.wand
  if os.clock() - lastSeatAt < 0.5 then return end
  local cur
  pcall(function() cur = pawn[wm.handItemProp or "CurHandItemFirstPerson"] end)
  if ctx.uehelp.isValid(cur) and ctx.uehelp.className(cur) == m.rodHandClass then
    defer(150, armRodHook)
    return -- already holding a live rod actor (an echo of our own seat)
  end
  local rodCls = resolveClass(m.rodHandClass)
  if not rodCls then return end
  lastSeatAt = os.clock()
  ctx.uehelp.call(pawn, wm.handBlueprintFn, rodCls) -- spawn+attach the game's own rod actor
  ctx.uehelp.call(pawn, m.equipModeFn, 0)           -- what the game's fishing branch does
  pcall(function()
    -- the fishing pose; harmless no-op if the anim names moved on an update
    local anim = pawn[m.handsMeshProp]:GetAnimInstance()
    if anim then anim[m.animItemEnumProp] = m.animItemEnumValue end
  end)
  ctx.log.info("fishing: the diamond rod gleams in your hand")
  defer(200, armRodHook)
end

-- Deferred body of the UpdateHandMeshesAndModes hook -- the ONE equip chokepoint (hotbar
-- switches AND every UI close funnel through it).
local function onHandRebuilt(pawn)
  if not ctx.uehelp.isValid(pawn) then return end
  local kind = heldRodKind(pawn)
  local was = diamondHeld
  diamondHeld = (kind == "diamond")
  if kind == "diamond" then
    seatDiamond(pawn)
  elseif kind == "vanilla" then
    defer(200, armRodHook) -- the game seats its own rod actor; hook its ChanceForLoot
  end
  if diamondHeld ~= was then
    ctx.log.info(diamondHeld and "fishing: x2 luck while the diamond rod is in hand"
                             or "fishing: the diamond rod is stowed")
    checkMult("rod")
  end
end

--------------------------------------------------------------------- hooks (qol re-arm pattern)
local function clearHooks()
  for key, h in pairs(hooked) do
    if type(h) == "table" and h.path then pcall(UnregisterHook, h.path, h[1], h[2]) end
    hooked[key] = nil
  end
end

local function armHook(ownerClass, fnName, tag, body)
  if not (ownerClass and fnName) then return false end
  local key = tostring(ownerClass) .. ":" .. fnName
  if hooked[key] then return true end
  local inst = ctx.uehelp.findFirst(ownerClass)
  if not inst then return false end
  local path = fullFuncPath(inst, fnName)
  if not path then return false end
  local ok, pre, post = pcall(RegisterHook, path, ctx.log.guard(tag, body))
  if ok then
    hooked[key] = { pre, post, path = path }
    ctx.log.debug("fishing: hooked " .. path)
  end
  return ok == true
end

armRodHook = function()
  local m = ctx.map.fishing
  armHook(m.rodHandClass, m.lootTickFn, "fishing.bite", function(Context)
    -- hook body: stash the instance and get out (the one thing a body may safely do)
    local rod
    pcall(function() rod = Context:get() end)
    if not rod then return end
    deferOnly(0, function() onGameThread(function() onLootTick(rod) end) end)
  end)
end

local function armClickHooks()
  local pawn = ctx.uehelp.findFirst(ctx.map.pawn and ctx.map.pawn.class)
  if not pawn then return end
  local wm = ctx.map.wand
  local exact, prefix = wm.castFnExact, wm.castFnPrefix
  local paths = {}
  pcall(function()
    pawn:GetClass():ForEachFunction(function(fn)
      local n = ""
      pcall(function() n = fn:GetFName():ToString() end)
      if (exact and n == exact) or (prefix and n:sub(1, #prefix) == prefix) then
        local full
        pcall(function() full = fn:GetFullName() end)
        if full then paths[#paths + 1] = (full:gsub("^%S+%s+", "")) end
      end
    end)
  end)
  for _, path in ipairs(paths) do
    if not hooked["click:" .. path] then
      local ok, pre, post = pcall(RegisterHook, path, ctx.log.guard("fishing.click", function(Context)
        local p
        pcall(function() p = Context:get() end)
        if not p then return end
        deferOnly(0, function() onGameThread(function() onClick(p) end) end)
      end))
      if ok then hooked["click:" .. path] = { pre, post, path = path } end
    end
  end
end

local function armHooks()
  local pawnClass = ctx.map.pawn and ctx.map.pawn.class
  armHook(pawnClass, ctx.map.wand and ctx.map.wand.handRebuildFn, "fishing.equip", function(Context)
    local p
    pcall(function() p = Context:get() end)
    if not p then return end
    deferOnly(150, function() onGameThread(function() onHandRebuilt(p) end) end)
  end)
  armClickHooks()
  armRodHook() -- no-op until a rod hand actor is resident; re-tried on every equip
end

--------------------------------------------------------------------- world lifecycle
local function applyAll()
  local pcNow
  pcall(function()
    local pc = ctx.uehelp.localController(ctx.map.player and ctx.map.player.controllerClass)
    pcNow = pc and pc:GetFullName() or nil
  end)
  if pcNow and pcNow ~= hookWorldPc then
    -- new world = reloaded classes: dead hooks, dead class refs, a dead half-played minigame
    hookWorldPc = pcNow
    clearHooks()
    classCache = {}
    splashWave = nil
    structMembers, structMemberTries = nil, 0
    tablesBroken = false
    mgReady, mgPending, mgActive, mgRiver, mgW = nil, false, false, nil, {}
    mgToken = mgToken + 1
    lastAppliedKey = nil
    diamondHeld = false
    lastIsDay = nil
    stormNow = (ctx.services.isStormy and ctx.services.isStormy()) or false
  end
  armHooks()
  -- rivers stream in with the level; spaced passes catch the stragglers (idempotent writes)
  for _, ms in ipairs({ 3000, 12000, 30000 }) do
    defer(ms, ctx.log.guard("fishing.tables", function()
      onGameThread(function()
        armHooks()
        F.applyTables("world")
        probeBar()
      end)
    end))
  end
end

local seenPawn = nil
local function onCharacter()
  local pawn = ctx.uehelp.playerPawn(ctx.map.pawn and ctx.map.pawn.class)
  local fn
  if pawn then pcall(function() fn = pawn:GetFullName() end) end
  if fn and fn ~= seenPawn then
    seenPawn = fn
    applyAll()
  else
    armHooks() -- cheap and idempotent; catches late-loading classes
  end
end

--------------------------------------------------------------------- init
function F.init(c)
  ctx = c
  if not ctx.config.get("fishing_enabled") then
    ctx.log.info("fishing: disabled by config")
    return false
  end
  if not ctx.gate.require(ctx.log, ctx.map, "fishing",
      { "fishing.riverClass", "fishing.loottableProp", "fishing.lootItemField",
        "fishing.lootWeightField", "fishing.rodHandClass", "fishing.lootTickFn" }) then
    return false
  end

  -- luck-state feeds
  ctx.bus.on("weather.changed", function(ev)
    stormNow = ev and ev.storm == true
    checkMult("storm")
  end)
  dayToken = dayToken + 1
  dayWatch(dayToken)

  -- world entry / respawn / hot reload (the qol shape: every Character construction funnels here)
  ctx.uehelp.onNewInstance("/Script/Engine.Actor", ctx.map.pawn and ctx.map.pawn.class,
    ctx.log.guard("fishing.character", function()
      deferOnly(400, function() onGameThread(onCharacter) end)
    end))
  -- a rod hand actor appearing = someone started fishing on this machine: hook its bite tick
  ctx.uehelp.onNewInstance("/Script/Engine.Actor", ctx.map.fishing.rodHandClass,
    ctx.log.guard("fishing.rodspawn", function()
      deferOnly(300, function() onGameThread(armRodHook) end)
    end))

  pcall(function()
    RegisterConsoleCommandHandler("sps_fish", function()
      local mult, twilight = currentMult()
      ctx.log.info(string.format(
        "fishing: mult x%.1f (diamond=%s storm=%s twilight=%s) tables=%s minigame=%s",
        mult, tostring(diamondHeld), tostring(stormNow), tostring(twilight),
        tablesBroken and "BROKEN" or "ok", tostring(mgReady)))
      return true
    end)
    RegisterConsoleCommandHandler("sps_fish_tables", function()
      onGameThread(function() F.applyTables("console") end)
      return true
    end)
    RegisterConsoleCommandHandler("sps_fish_mini", function()
      forceMini = not forceMini
      ctx.log.info("fishing: skillshot on EVERY bite " .. (forceMini and "ON (testing)" or "off"))
      return true
    end)
  end)

  applyAll()
  ctx.log.info("fishing: ready -- new tables, storm/twilight/diamond luck, worn rods, skillshot")
  return true
end

return F
